### PR TITLE
wifi support

### PR DESCRIPTION
**Pull request by josematheus10**
configure wifi connection on plist
string: 'BATATA'

### CODE REVIEW

**Comment by csrutil** [comment]
@josematheus10 Thank you for your contribution, I put the itlwm to the kext folder today. you can try the latest EFI

**Comment by Tobix99** [comment]
Is this supposed to be working? Because on my Nuc the Wifi didn't work, until I installed a Broadcom Wifi chip in the m.2 slot.

**Comment by ranXeron** [comment]
wifi works with itlwm.kext and heliport.dmg    [https://github.com/OpenIntelWireless](url)

**Comment by Tobix99** [comment]
@ranXeron Yes, I saw this driver, but after I ordered a Broadcom Module, so I doesn't affect me anymore, but I've read this thread and thought, that the Intel Driver maybe should work out of the box.

**Comment by josematheus10** [comment]
Its work in this hardware: [https://ibb.co/sqjG45N](https://ibb.co/sqjG45N)

**Comment by Tobix99** [comment]
@josematheus10 Interesting, I think I have this exact same chip in my Nuc8-i5BEH, but it doesn't work out of the box with the efi from this repo. OpenIntelWireless will work (I think). But I saw this pull request and wondered, why it never worked for me out of the box with the EFI and Kext files provided here.

**Pull request closed without merging**
